// data.js — 全4ジャンルのデータ

export const SURNAME_DATA = {
  top50: {
    "佐藤": { rank: 1, count: "約183万人" }, "鈴木": { rank: 2, count: "約176万人" },
    "高橋": { rank: 3, count: "約138万人" }, "田中": { rank: 4, count: "約131万人" },
    "伊藤": { rank: 5, count: "約105万人" }, "渡辺": { rank: 6, count: "約104万人" },
    "山本": { rank: 7, count: "約102万人" }, "中村": { rank: 8, count: "約102万人" },
    "小林": { rank: 9, count: "約101万人" }, "加藤": { rank: 10, count: "約87万人" },
    "吉田": { rank: 11, count: "約81万人" }, "山田": { rank: 12, count: "約79万人" },
    "佐々木": { rank: 13, count: "約65万人" }, "山口": { rank: 14, count: "約63万人" },
    "松本": { rank: 15, count: "約61万人" }, "井上": { rank: 16, count: "約60万人" },
    "木村": { rank: 17, count: "約56万人" }, "林": { rank: 18, count: "約53万人" },
    "斎藤": { rank: 19, count: "約53万人" }, "清水": { rank: 20, count: "約52万人" },
    "山崎": { rank: 21, count: "約47万人" }, "森": { rank: 22, count: "約45万人" },
    "池田": { rank: 23, count: "約44万人" }, "橋本": { rank: 24, count: "約43万人" },
    "阿部": { rank: 25, count: "約43万人" }, "石川": { rank: 26, count: "約42万人" },
    "山下": { rank: 27, count: "約41万人" }, "中島": { rank: 28, count: "約39万人" },
    "石井": { rank: 29, count: "約39万人" }, "小川": { rank: 30, count: "約39万人" },
    "前田": { rank: 31, count: "約37万人" }, "岡田": { rank: 32, count: "約37万人" },
    "長谷川": { rank: 33, count: "約37万人" }, "藤田": { rank: 34, count: "約36万人" },
    "後藤": { rank: 35, count: "約36万人" }, "近藤": { rank: 36, count: "約36万人" },
    "村上": { rank: 37, count: "約34万人" }, "遠藤": { rank: 38, count: "約32万人" },
    "青木": { rank: 39, count: "約32万人" }, "坂本": { rank: 40, count: "約31万人" },
    "斉藤": { rank: 41, count: "約31万人" }, "福田": { rank: 42, count: "約30万人" },
    "太田": { rank: 43, count: "約30万人" }, "西村": { rank: 44, count: "約30万人" },
    "藤井": { rank: 45, count: "約30万人" }, "金子": { rank: 46, count: "約29万人" },
    "岡本": { rank: 47, count: "約29万人" }, "藤原": { rank: 48, count: "約28万人" },
    "中野": { rank: 49, count: "約28万人" }, "三浦": { rank: 50, count: "約28万人" },
  },
  near: {
    "原田": { rank: 51, count: "約28万人" }, "中川": { rank: 52, count: "約28万人" },
    "松田": { rank: 53, count: "約27万人" }, "竹内": { rank: 54, count: "約27万人" },
    "小野": { rank: 55, count: "約26万人" }, "田村": { rank: 56, count: "約26万人" },
    "中山": { rank: 57, count: "約26万人" }, "和田": { rank: 58, count: "約25万人" },
    "石田": { rank: 59, count: "約25万人" }, "森田": { rank: 60, count: "約25万人" },
    "上田": { rank: 61, count: "約24万人" }, "内田": { rank: 62, count: "約23万人" },
    "原": { rank: 63, count: "約23万人" }, "柴田": { rank: 64, count: "約23万人" },
    "酒井": { rank: 65, count: "約23万人" }, "宮崎": { rank: 66, count: "約22万人" },
    "横山": { rank: 67, count: "約22万人" }, "高木": { rank: 68, count: "約22万人" },
    "安藤": { rank: 69, count: "約22万人" }, "宮本": { rank: 70, count: "約22万人" },
    "大野": { rank: 71, count: "約21万人" }, "小島": { rank: 72, count: "約21万人" },
    "谷口": { rank: 73, count: "約21万人" }, "今井": { rank: 74, count: "約20万人" },
    "工藤": { rank: 75, count: "約20万人" }, "高田": { rank: 76, count: "約20万人" },
    "増田": { rank: 77, count: "約20万人" }, "丸山": { rank: 78, count: "約19万人" },
    "杉山": { rank: 79, count: "約19万人" }, "村田": { rank: 80, count: "約19万人" },
    "新井": { rank: 81, count: "約19万人" }, "大塚": { rank: 82, count: "約19万人" },
    "小山": { rank: 83, count: "約18万人" }, "平野": { rank: 84, count: "約18万人" },
    "藤本": { rank: 85, count: "約18万人" }, "野口": { rank: 86, count: "約18万人" },
    "河野": { rank: 87, count: "約18万人" }, "上野": { rank: 88, count: "約18万人" },
    "武田": { rank: 89, count: "約18万人" }, "松井": { rank: 90, count: "約18万人" },
    "岩崎": { rank: 91, count: "約17万人" }, "千葉": { rank: 92, count: "約17万人" },
    "菅原": { rank: 93, count: "約17万人" }, "木下": { rank: 94, count: "約17万人" },
    "久保": { rank: 95, count: "約17万人" }, "佐野": { rank: 96, count: "約17万人" },
    "野村": { rank: 97, count: "約17万人" }, "松尾": { rank: 98, count: "約17万人" },
    "市川": { rank: 99, count: "約17万人" }, "菊地": { rank: 100, count: "約17万人" },
  },
  // 異体字マッピング
  variants: {
    "渡邊": "渡辺", "渡邉": "渡辺",
    "齋藤": "斎藤", "齊藤": "斎藤", "齊籐": "斎藤", "齋籐": "斎藤",
    "斉籐": "斉藤",
    "髙橋": "高橋", "髙田": "高田", "髙木": "高木",
    "櫻本": "坂本",
  },
};

export const KANJI_DATA = {
  numberKanji: ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十"],
  allKanji: [
    "一", "右", "雨", "円", "王", "音", "下", "火", "花", "貝",
    "学", "気", "九", "休", "玉", "金", "空", "月", "犬", "見",
    "五", "口", "校", "左", "三", "山", "子", "四", "糸", "字",
    "耳", "七", "車", "手", "十", "出", "女", "小", "上", "森",
    "人", "水", "正", "生", "青", "夕", "石", "赤", "千", "川",
    "先", "早", "草", "足", "村", "大", "男", "竹", "中", "虫",
    "町", "天", "田", "土", "二", "日", "入", "年", "白", "八",
    "百", "文", "木", "本", "名", "目", "立", "力", "林", "六",
  ],
  aoriComments: [
    "残念！それは2年生の壁でしたね！",
    "まだあなたは幼稚園生ですね！ もう一度、初心に戻って考えましょう。",
    "おっと、そこは罠でしたね！タイムマシンで1年生に戻って再勉強だ！",
    "不正解！まさか、ここでアウトとは... 周りのチームも驚いていますよ！",
    "それは大人の漢字ですね！シンプルに考えましょう！",
    "うーん、惜しい！もう少しで正解でした。（大嘘）",
    "どんまい！次チームのターン！あなたのミスを彼らがどう生かすか見物ですね",
    "（ブーッという効果音）その漢字は封印されています！別の漢字をどうぞ！",
    "まさかの小学生レベルでつまずくとは... 懇親会後、補習授業ですね！",
    "漢字検定10級のテキストが泣いていますよ！",
  ],
};

export const KARAOKE_DATA = [
  { rank: 1,  title: "残酷な天使のテーゼ", artist: "高橋洋子", aliases: ["残酷な天使のテーゼ", "残酷な天使", "エヴァ"], yt: { id: "o6wtDPVkKqI", start: 55 } },
  { rank: 2,  title: "小さな恋のうた", artist: "MONGOL800", aliases: ["小さな恋のうた", "小さな恋", "モンパチ"], yt: { id: "u8EkSB9zSpE", start: 52 } },
  { rank: 3,  title: "ハナミズキ", artist: "一青窈", aliases: ["ハナミズキ", "花水木"], yt: { id: "Lv9pOboKtjg", start: 53 } },
  { rank: 4,  title: "チェリー", artist: "スピッツ", aliases: ["チェリー", "cherry"], yt: { id: "Eze6-eHmtJg", start: 62 } },
  { rank: 5,  title: "キセキ", artist: "GReeeeN", aliases: ["キセキ", "奇跡"], yt: { id: "DwTinTO0o9I", start: 82 } },
  { rank: 6,  title: "糸", artist: "中島みゆき", aliases: ["糸"], yt: { id: "78UwqbJnI18", start: 55 } },
  { rank: 7,  title: "サウダージ", artist: "ポルノグラフィティ", aliases: ["サウダージ", "saudade"], yt: { id: "lzsB4eKPdJI", start: 53 } },
  { rank: 8,  title: "未来予想図Ⅱ", artist: "DREAMS COME TRUE", aliases: ["未来予想図", "未来予想図2", "未来予想図II", "ドリカム"], yt: { id: "AYhxRUJxQYM", start: 75 } },
  { rank: 9,  title: "天体観測", artist: "BUMP OF CHICKEN", aliases: ["天体観測", "バンプ"], yt: { id: "j7CDb610Bg0", start: 68 } },
  { rank: 10, title: "I LOVE YOU", artist: "尾崎豊", aliases: ["i love you", "アイラブユー"], yt: { id: "EPUtO0gNHPA", start: 55 } },
  { rank: 11, title: "奏(かなで)", artist: "スキマスイッチ", aliases: ["奏", "かなで", "奏(かなで)"], yt: { id: "J5Z7tIq7bco", start: 80 } },
  { rank: 12, title: "アゲハ蝶", artist: "ポルノグラフィティ", aliases: ["アゲハ蝶", "アゲハ"], yt: { id: "zQq_cgH5_AI", start: 60 } },
  { rank: 13, title: "タッチ", artist: "岩崎良美", aliases: ["タッチ", "touch"], yt: { id: "WW6OgFqTNfg", start: 30 } },
  { rank: 14, title: "粉雪", artist: "レミオロメン", aliases: ["粉雪", "こなゆき"], yt: { id: "1wxTksLZ1Mw", start: 75 } },
  { rank: 15, title: "シングルベッド", artist: "シャ乱Q", aliases: ["シングルベッド"], yt: { id: "UYXNA54dDKs", start: 60 } },
  { rank: 16, title: "3月9日", artist: "レミオロメン", aliases: ["3月9日", "三月九日"], yt: { id: "UNRJyBHziX4", start: 65 } },
  { rank: 17, title: "TSUNAMI", artist: "サザンオールスターズ", aliases: ["tsunami", "ツナミ"], yt: { id: "xRyL5BPOWfE", start: 55 } },
  { rank: 18, title: "Lemon", artist: "米津玄師", aliases: ["lemon", "レモン"], yt: { id: "SX_ViT4Ra7k", start: 72 } },
  { rank: 19, title: "天城越え", artist: "石川さゆり", aliases: ["天城越え", "あまぎごえ"], yt: { id: "jVkQm4Fpui8", start: 55 } },
  { rank: 20, title: "愛唄", artist: "GReeeeN", aliases: ["愛唄", "あいうた"], yt: { id: "EvwRYGlJWfQ", start: 68 } },
  { rank: 21, title: "世界に一つだけの花", artist: "SMAP", aliases: ["世界に一つだけの花", "世界にひとつ", "セカハナ"], yt: { id: "n69cLnXHas4", start: 55 } },
  { rank: 22, title: "栄光の架橋", artist: "ゆず", aliases: ["栄光の架橋", "栄光のかけはし"], yt: { id: "PRJoAPH0ZGo", start: 72 } },
  { rank: 23, title: "Story", artist: "AI", aliases: ["story", "ストーリー"], yt: { id: "B2fPYlGKdXM", start: 62 } },
  { rank: 24, title: "そばかす", artist: "JUDY AND MARY", aliases: ["そばかす", "ジュディマリ"], yt: { id: "ewphY7jULL0", start: 28 } },
  { rank: 25, title: "fragile", artist: "Every Little Thing", aliases: ["fragile", "フラジール", "ELT"], yt: { id: "NP60Qqjfdhs", start: 60 } },
  { rank: 26, title: "花", artist: "オレンジレンジ", aliases: ["花 オレンジレンジ"], yt: { id: "iYkg90hDInc", start: 50 } },
  { rank: 27, title: "千本桜", artist: "WhiteFlame feat.初音ミク", aliases: ["千本桜", "せんぼんざくら"], yt: { id: "shs0rAiwsGQ", start: 38 } },
  { rank: 28, title: "366日", artist: "HY", aliases: ["366日", "366"], yt: { id: "NeehvcFqLX8", start: 62 } },
  { rank: 29, title: "HOWEVER", artist: "GLAY", aliases: ["however", "ハウエバー"], yt: { id: "gPcPseeICjs", start: 60 } },
  { rank: 30, title: "夏祭り", artist: "Whiteberry", aliases: ["夏祭り", "なつまつり"], yt: { id: "AZRR01YOKcM", start: 32 } },
];

export const MOVIE_DATA = [
  { rank: 1,  title: "劇場版「鬼滅の刃」無限列車編", revenue: "407.5億円", aliases: ["鬼滅の刃", "無限列車", "鬼滅"] },
  { rank: 2,  title: "劇場版「鬼滅の刃」無限城編 第一章", revenue: "397.0億円", aliases: ["無限城", "無限城編", "鬼滅 無限城"] },
  { rank: 3,  title: "千と千尋の神隠し", revenue: "316.8億円", aliases: ["千と千尋", "千と千尋の神隠し"] },
  { rank: 4,  title: "タイタニック", revenue: "277.7億円", aliases: ["タイタニック", "titanic"] },
  { rank: 5,  title: "アナと雪の女王", revenue: "255.0億円", aliases: ["アナ雪", "アナと雪の女王", "frozen"] },
  { rank: 6,  title: "君の名は。", revenue: "251.7億円", aliases: ["君の名は", "きみのなは"] },
  { rank: 7,  title: "もののけ姫", revenue: "214.6億円", aliases: ["もののけ姫", "もののけ"] },
  { rank: 8,  title: "ONE PIECE FILM RED", revenue: "203.4億円", aliases: ["ワンピース", "one piece", "FILM RED"] },
  { rank: 9,  title: "ハリー・ポッターと賢者の石", revenue: "203.0億円", aliases: ["ハリーポッター", "ハリポタ", "賢者の石"] },
  { rank: 10, title: "国宝", revenue: "202.7億円", aliases: ["国宝"] },
  { rank: 11, title: "ハウルの動く城", revenue: "196.0億円", aliases: ["ハウル", "ハウルの動く城"] },
  { rank: 12, title: "踊る大捜査線 THE MOVIE2", revenue: "173.5億円", aliases: ["踊る大捜査線", "踊る"] },
  { rank: 13, title: "ハリー・ポッターと秘密の部屋", revenue: "173.0億円", aliases: ["秘密の部屋"] },
  { rank: 14, title: "THE FIRST SLAM DUNK", revenue: "166.7億円", aliases: ["スラムダンク", "slam dunk", "SLAM DUNK"] },
  { rank: 15, title: "アバター", revenue: "159.0億円", aliases: ["アバター", "avatar"] },
  { rank: 16, title: "名探偵コナン 100万ドルの五稜星", revenue: "158.0億円", aliases: ["コナン 五稜星", "100万ドル", "五稜星"] },
  { rank: 17, title: "崖の上のポニョ", revenue: "155.0億円", aliases: ["ポニョ", "崖の上のポニョ"] },
  { rank: 18, title: "ズートピア2", revenue: "154.0億円", aliases: ["ズートピア", "zootopia"] },
  { rank: 19, title: "すずめの戸締まり", revenue: "149.4億円", aliases: ["すずめの戸締まり", "すずめ"] },
  { rank: 20, title: "名探偵コナン 隻眼の残像", revenue: "147.4億円", aliases: ["コナン 隻眼", "隻眼の残像"] },
  { rank: 21, title: "天気の子", revenue: "142.3億円", aliases: ["天気の子"] },
  { rank: 22, title: "ザ・スーパーマリオブラザーズ・ムービー", revenue: "140.2億円", aliases: ["マリオ", "スーパーマリオ", "マリオブラザーズ"] },
  { rank: 23, title: "劇場版 呪術廻戦 0", revenue: "138.9億円", aliases: ["呪術廻戦", "呪術"] },
  { rank: 24, title: "名探偵コナン 黒鉄の魚影", revenue: "138.8億円", aliases: ["コナン 黒鉄", "黒鉄の魚影"] },
  { rank: 25, title: "トップガン マーヴェリック", revenue: "138.1億円", aliases: ["トップガン", "top gun", "マーヴェリック"] },
  { rank: 26, title: "ラスト・サムライ", revenue: "137.0億円", aliases: ["ラストサムライ", "last samurai"] },
  { rank: 27, title: "ボヘミアン・ラプソディ", revenue: "135.1億円", aliases: ["ボヘミアンラプソディ", "bohemian"] },
  { rank: 28, title: "E.T.", revenue: "135.0億円", aliases: ["ET", "E.T.", "イーティー"] },
  { rank: 29, title: "アルマゲドン", revenue: "135.0億円", aliases: ["アルマゲドン", "armageddon"] },
  { rank: 30, title: "ハリー・ポッターとアズカバンの囚人", revenue: "135.0億円", aliases: ["アズカバン", "アズカバンの囚人"] },
];
